#Application configurations
server:
  port: 9000
spring:
  application:
    name: gate-way

#Eureka config
eureka:
  client:
    serviceUrl:
      fetchRegistry: true
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
